-- Migration: Add range partitioning to Posts and Comments tables
-- Purpose: Optimize query performance for 400k+ users by partitioning large tables by month
-- 
-- IMPORTANT: This migration requires careful execution:
-- 1. Should be run during a maintenance window
-- 2. Data migration may take significant time depending on table size
-- 3. Test in staging environment first
--
-- Rollback: See 0028_rollback_posts_comments_partitioning.sql
--
-- ORM COMPATIBILITY NOTE:
-- The partitioned tables use a composite primary key (id, timestamp) as required by PostgreSQL.
-- A UNIQUE constraint on id is added to maintain ORM relationship compatibility.
-- Drizzle ORM and other ORMs can reference Post by id alone for joins/FKs.
--
-- FOREIGN KEY NOTE:
-- Foreign keys are NOT enforced at the database level on partitioned tables due to PostgreSQL
-- limitations with partitioned FK constraints. Referential integrity must be enforced at the
-- application level. The ORM schema should validate postId/authorId references before inserts.

-- ============================================================================
-- Step 1: Create partitioned Post table
-- ============================================================================

-- Create the new partitioned table structure
-- Note: PRIMARY KEY (id, timestamp) is required for PostgreSQL partitioning
-- UNIQUE (id) is added for ORM compatibility and FK references
CREATE TABLE IF NOT EXISTS "Post_partitioned" (
    id text NOT NULL,
    content text NOT NULL,
    "authorId" text NOT NULL,
    "gameId" text,
    "dayNumber" integer,
    timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "articleTitle" text,
    "articleContent" text,
    "originalPostId" text,
    "commentOnPostId" text,
    hashtags text[],
    "editedAt" timestamp,
    "deletedAt" timestamp,
    "articleImageUrl" text,
    "lastActivityAt" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, timestamp)
    -- NOTE: Global UNIQUE(id) is NOT possible on PostgreSQL partitioned tables.
    -- PostgreSQL requires UNIQUE constraints to include all partition key columns.
    -- ID uniqueness is enforced at the application level via UUID generation.
    -- ORM relationships work because IDs are globally unique UUIDs generated by the app.
) PARTITION BY RANGE (timestamp);

-- Create partitions starting from Dec 2025 (when data began)
-- Note: No pre-Dec-2025 partitions needed as no historical data exists
CREATE TABLE IF NOT EXISTS "Post_2025_12" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- 2026 partitions (current year + future)
CREATE TABLE IF NOT EXISTS "Post_2026_01" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS "Post_2026_02" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS "Post_2026_03" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE IF NOT EXISTS "Post_2026_04" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE IF NOT EXISTS "Post_2026_05" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE IF NOT EXISTS "Post_2026_06" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE IF NOT EXISTS "Post_2026_07" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS "Post_2026_08" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS "Post_2026_09" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS "Post_2026_10" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS "Post_2026_11" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS "Post_2026_12" PARTITION OF "Post_partitioned"
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- Default partition for any data outside defined ranges
CREATE TABLE IF NOT EXISTS "Post_default" PARTITION OF "Post_partitioned" DEFAULT;

-- ============================================================================
-- Step 2: Create indexes on partitioned Post table
-- ============================================================================

-- These indexes will be created on each partition automatically
CREATE INDEX IF NOT EXISTS "Post_partitioned_authorId_idx" ON "Post_partitioned" ("authorId");
CREATE INDEX IF NOT EXISTS "Post_partitioned_timestamp_idx" ON "Post_partitioned" (timestamp DESC);
CREATE INDEX IF NOT EXISTS "Post_partitioned_authorId_timestamp_idx" ON "Post_partitioned" ("authorId", timestamp DESC);
CREATE INDEX IF NOT EXISTS "Post_partitioned_gameId_idx" ON "Post_partitioned" ("gameId") WHERE "gameId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "Post_partitioned_originalPostId_idx" ON "Post_partitioned" ("originalPostId") WHERE "originalPostId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "Post_partitioned_deletedAt_idx" ON "Post_partitioned" ("deletedAt") WHERE "deletedAt" IS NULL;

-- ============================================================================
-- Step 3: Create partitioned Comment table
-- ============================================================================

-- Note: PRIMARY KEY (id, createdAt) required for PostgreSQL partitioning
-- FOREIGN KEY constraints are NOT added due to PostgreSQL partitioning limitations
-- Application-level validation must ensure postId references valid Post.id and
-- authorId references valid User.id before insert
CREATE TABLE IF NOT EXISTS "Comment_partitioned" (
    id text NOT NULL,
    content text NOT NULL,
    "postId" text NOT NULL,
    "authorId" text NOT NULL,
    "parentCommentId" text,
    "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" timestamp,
    PRIMARY KEY (id, "createdAt")
    -- NOTE: Global UNIQUE(id) is NOT possible on PostgreSQL partitioned tables.
    -- ID uniqueness is enforced at the application level via UUID generation.
) PARTITION BY RANGE ("createdAt");

-- Create Comment partitions starting from Dec 2025 (when data began)
CREATE TABLE IF NOT EXISTS "Comment_2025_12" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- 2026 partitions
CREATE TABLE IF NOT EXISTS "Comment_2026_01" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_02" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_03" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_04" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_05" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_06" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_07" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_08" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_09" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_10" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_11" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS "Comment_2026_12" PARTITION OF "Comment_partitioned"
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- Default partition
CREATE TABLE IF NOT EXISTS "Comment_default" PARTITION OF "Comment_partitioned" DEFAULT;

-- ============================================================================
-- Step 4: Create indexes on partitioned Comment table
-- ============================================================================

CREATE INDEX IF NOT EXISTS "Comment_partitioned_postId_idx" ON "Comment_partitioned" ("postId");
CREATE INDEX IF NOT EXISTS "Comment_partitioned_authorId_idx" ON "Comment_partitioned" ("authorId");
CREATE INDEX IF NOT EXISTS "Comment_partitioned_createdAt_idx" ON "Comment_partitioned" ("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "Comment_partitioned_postId_createdAt_idx" ON "Comment_partitioned" ("postId", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS "Comment_partitioned_parentCommentId_idx" ON "Comment_partitioned" ("parentCommentId") WHERE "parentCommentId" IS NOT NULL;

-- ============================================================================
-- Step 5: Create function to auto-create future partitions
-- ============================================================================

CREATE OR REPLACE FUNCTION create_future_partitions()
RETURNS void AS $$
DECLARE
    partition_date DATE;
    partition_name TEXT;
    start_date TEXT;
    end_date TEXT;
BEGIN
    -- Create partitions for the next 3 months if they don't exist
    FOR i IN 0..2 LOOP
        partition_date := DATE_TRUNC('month', CURRENT_DATE + (i || ' months')::INTERVAL);
        
        -- Post partitions
        partition_name := 'Post_' || TO_CHAR(partition_date, 'YYYY_MM');
        start_date := TO_CHAR(partition_date, 'YYYY-MM-DD');
        end_date := TO_CHAR(partition_date + '1 month'::INTERVAL, 'YYYY-MM-DD');
        
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF "Post_partitioned" FOR VALUES FROM (%L) TO (%L)',
            partition_name, start_date, end_date
        );
        
        -- Comment partitions
        partition_name := 'Comment_' || TO_CHAR(partition_date, 'YYYY_MM');
        
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF "Comment_partitioned" FOR VALUES FROM (%L) TO (%L)',
            partition_name, start_date, end_date
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Step 6: Data migration (run separately in production)
-- ============================================================================

-- NOTE: This section should be run in batches during a maintenance window.
-- The actual data migration is commented out and should be run manually.
-- 
-- For production deployment:
-- 1. Create the partitioned tables first (Steps 1-5 above)
-- 2. Run data migration in batches (data starts Dec 2025):
--    INSERT INTO "Post_partitioned" SELECT * FROM "Post" WHERE timestamp >= '2025-12-01' AND timestamp < '2026-01-01';
--    INSERT INTO "Post_partitioned" SELECT * FROM "Post" WHERE timestamp >= '2026-01-01' AND timestamp < '2026-02-01';
--    -- Repeat for each month's data that exists
-- 3. Once all data is migrated and verified:
--    ALTER TABLE "Post" RENAME TO "Post_unpartitioned";
--    ALTER TABLE "Post_partitioned" RENAME TO "Post";
-- 4. Update foreign key references
-- 5. Drop old tables after verification period

-- ============================================================================
-- Step 7: Create views for backward compatibility during migration
-- ============================================================================

-- These views allow application code to work with both old and new tables
-- during the migration period

-- IMPORTANT: The actual table swap should be done manually after data migration
-- DO NOT run the following in production without proper testing:
--
-- BEGIN;
-- ALTER TABLE "Post" RENAME TO "Post_unpartitioned";
-- ALTER TABLE "Post_partitioned" RENAME TO "Post";
-- ALTER TABLE "Comment" RENAME TO "Comment_unpartitioned";
-- ALTER TABLE "Comment_partitioned" RENAME TO "Comment";
-- COMMIT;

-- ============================================================================
-- Step 8: Post-Migration Verification (REQUIRED before table swap)
-- ============================================================================

-- Run these verification queries AFTER data migration and BEFORE renaming tables:

-- 8.1 Row count comparison
-- SELECT 'Original Post count' as table_name, COUNT(*) as row_count FROM "Post"
-- UNION ALL
-- SELECT 'Partitioned Post count', COUNT(*) FROM "Post_partitioned"
-- UNION ALL
-- SELECT 'Original Comment count', COUNT(*) FROM "Comment"
-- UNION ALL
-- SELECT 'Partitioned Comment count', COUNT(*) FROM "Comment_partitioned";

-- 8.2 Partition distribution check (verify no excessive data in default partition)
-- Uses pg_stat_user_tables for row count estimates (n_live_tup) to avoid dynamic SQL
-- SELECT 
--     c.relname as partition_name,
--     pg_size_pretty(pg_relation_size(c.oid)) as size,
--     COALESCE(s.n_live_tup, 0) as row_count_estimate
-- FROM pg_class c
-- JOIN pg_inherits i ON c.oid = i.inhrelid
-- LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid
-- WHERE i.inhparent = '"Post_partitioned"'::regclass
-- ORDER BY c.relname;

-- 8.3 Spot-check recent rows
-- SELECT id, timestamp, content FROM "Post_partitioned" 
-- ORDER BY timestamp DESC LIMIT 10;
-- 
-- SELECT id, "createdAt", content FROM "Comment_partitioned"
-- ORDER BY "createdAt" DESC LIMIT 10;

-- 8.4 Verify default partition is empty or minimal
-- SELECT COUNT(*) as default_partition_rows FROM ONLY "Post_default";
-- SELECT COUNT(*) as default_partition_rows FROM ONLY "Comment_default";

-- ONLY proceed with ALTER TABLE RENAME after all verification passes!

-- ============================================================================
-- Step 9: Scheduling create_future_partitions()
-- ============================================================================

-- The create_future_partitions() function must be called regularly to ensure
-- new partitions exist before data arrives. Options:

-- OPTION A: pg_cron (recommended for PostgreSQL)
-- Requires pg_cron extension: CREATE EXTENSION pg_cron;
-- Schedule monthly on the 1st at midnight:
-- SELECT cron.schedule('create-future-partitions', '0 0 1 * *', 'SELECT create_future_partitions()');

-- OPTION B: Application bootstrap
-- Call from application startup or deployment hooks:
-- await db.execute(sql`SELECT create_future_partitions()`);

-- OPTION C: External cron job
-- Add to system crontab or CI/CD pipeline:
-- 0 0 1 * * psql -c "SELECT create_future_partitions()" your_database

-- WARNING: If partitions are not created in advance, new data will go to
-- Post_default/Comment_default, causing a performance hotspot.
