/**
 * Babylon Question Manager
 *
 * @module engine/QuestionManager
 *
 * @description
 * Manages the complete lifecycle of prediction market questions in the Babylon game.
 * Questions are the core mechanic that drives events, NPC behavior, and player betting.
 *
 * **Core Responsibilities:**
 * - Generate new questions daily (1-3 per day) based on scenarios and recent events
 * - Track active questions (max 20 concurrent)
 * - Resolve questions when resolution date is reached (24h-7d from creation)
 * - Generate resolution events that definitively prove outcomes
 * - Ensure game events are aligned with active questions
 *
 * **Question Lifecycle:**
 * 1. **Creation** - Generated by LLM with resolutionDate 24h-7d in future
 * 2. **Active** - Appears in markets, events generated around it, tradable
 * 3. **Resolved** - Outcome determined, positions settled, no longer tradable
 * 4. **Cancelled** - Removed without resolution (rare, edge cases only)
 *
 * **Generation Strategy:**
 * - Uses LLM to create contextually relevant questions
 * - Considers recent events and current storylines
 * - Avoids duplicate or overlapping questions
 * - Ensures questions align with available actors and organizations
 *
 * **Resolution Timing:**
 * - Questions resolve 1-7 days after creation
 * - Longer timespans for complex questions (mergers, investigations)
 * - Shorter timespans for urgent developments (announcements, scandals)
 * - Resolution event generated to prove outcome definitively
 *
 * @see {@link executeGameTick} - Production tick uses QuestionManager to generate questions and resolution proofs
 * @see {@link FeedGenerator} - Creates posts and discussions about active questions
 *
 * @example
 * ```typescript
 * const qm = new QuestionManager(llmClient);
 *
 * // Generate new questions
 * const questions = await qm.generateDailyQuestions({
 *   currentDate: '2025-10-15',
 *   scenarios,
 *   actors,
 *   organizations,
 *   activeQuestions: [],
 *   recentEvents: [],
 *   nextQuestionId: 1
 * });
 *
 * // Check for questions to resolve
 * const toResolve = qm.getQuestionsToResolve(activeQuestions, '2025-10-16');
 *
 * // Resolve a question
 * const resolved = qm.resolveQuestion(question, true); // true = YES outcome
 * ```
 */

import {
  PredictionDbAdapter as CorePredictionDbAdapter,
  PredictionMarketService as CorePredictionMarketService,
} from '@babylon/core/markets/prediction';
import {
  and,
  db,
  desc,
  eq,
  gte,
  questions,
  tags,
  trendingTags,
  worldEvents,
} from '@babylon/db';
import {
  generateSnowflakeId,
  logger,
  RESOLUTION_CONFIDENCE_CONFIG,
} from '@babylon/shared';
import { type Article, ArticleGenerator } from './ArticleGenerator';
import type { BabylonLLMClient } from './llm/openai-client';
import { BabylonLLMClient as BabylonLLMClientValue } from './llm/openai-client';
import { MarketDecisionEngine } from './MarketDecisionEngine';
import {
  generateWorldContext,
  questionGeneration,
  questionResolutionValidation,
  renderPrompt,
  worldImpactAssessment,
} from './prompts';
import { MarketContextService } from './services/market-context-service';
import { MarketMetricsService } from './services/market-metrics-service';
import { saveArcPlan } from './services/narrative-state-service';
import { ensureMarketOnChain } from './services/onchain-market-service';
import { QuestionArcPlanner } from './services/question-arc-planner';
import { StaticDataRegistry } from './services/static-data-registry';
import { TradeExecutionService } from './services/trade-execution-service';
import type {
  DayTimeline,
  Organization,
  Question,
  Scenario,
  SelectedActor,
  WorldEvent,
} from './types/shared';
import { firstOrThrow } from './utils/array-utils';
import { toDateString } from './utils/date-utils';
import { formatError } from './utils/error-utils';
import { clamp } from './utils/math-utils';
import { shuffleArray } from './utils/randomization';
import { worldFactsService } from './world-facts-service';

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Determines if an actor is eligible for question generation.
 * Actors are eligible if they have a main/supporting role OR are S/A tier.
 * This handles cases where actors may not have a role defined but do have a tier.
 *
 * Exported for reuse in other modules (e.g., markets-tick).
 */
export function isEligibleActor(actor: {
  role?: string | null;
  tier?: string | null;
}): boolean {
  return (
    actor.role === 'main' ||
    actor.role === 'supporting' ||
    actor.tier === 'S_TIER' ||
    actor.tier === 'A_TIER'
  );
}

/**
 * Parameters for question generation
 *
 * @interface QuestionCreationParams
 *
 * @property currentDate - ISO date string (YYYY-MM-DD) for the generation date
 * @property scenarios - Available game scenarios for context
 * @property actors - Available actors (filtered to main/supporting roles)
 * @property organizations - Available organizations (companies, media, etc.)
 * @property activeQuestions - Currently active questions (to avoid duplicates)
 * @property recentEvents - Recent game history for context
 * @property nextQuestionId - Next available numeric ID for new questions
 */
export interface QuestionCreationParams {
  currentDate: string;
  scenarios: Scenario[];
  actors: SelectedActor[];
  organizations: Organization[];
  activeQuestions: Question[];
  recentEvents: DayTimeline[];
  nextQuestionId: number;
}

/**
 * Resolution with proof and confidence assessment
 *
 * Returned by generateResolutionWithProof containing the resolution description,
 * optional proof article, and confidence metrics for manual review flagging.
 */
export interface ResolutionWithProof {
  /** Natural language description of why/how the question resolved */
  description: string;
  /** Optional proof article with URL */
  proof?: { type: 'article'; article: Article; url: string };
  /** Confidence score (0-1) based on speculative signal detection */
  confidence: number;
  /** Whether this resolution requires manual admin review */
  requiresManualReview: boolean;
  /** Detected speculative signals that reduced confidence */
  confidenceSignals: string[];
}

/**
 * Question Manager - Handles question lifecycle
 *
 * @class QuestionManager
 *
 * @description
 * Central manager for all prediction market questions. Uses LLM to generate
 * contextually relevant questions and manages their lifecycle from creation
 * through resolution.
 *
 * **Key Methods:**
 * - `generateDailyQuestions()` - Create 1-3 new questions per day
 * - `getQuestionsToResolve()` - Find questions ready to resolve
 * - `resolveQuestion()` - Mark question as resolved with final outcome
 * - `generateResolutionEvent()` - Create definitive proof of outcome
 *
 * @usage
 * Instantiated once by GameEngine and used throughout the game lifecycle.
 */
export class QuestionManager {
  private llm: BabylonLLMClient;

  /**
   * Create a new QuestionManager instance
   *
   * @param llm - Babylon LLM client for question generation
   */
  constructor(llm: BabylonLLMClient) {
    this.llm = llm;
  }

  /**
   * Generate new questions for the current day
   *
   * @param params - Question creation parameters including context and IDs
   * @returns Array of newly generated questions (1-3 questions, empty if at capacity)
   *
   * @description
   * Uses LLM to generate contextually relevant prediction market questions based on
   * recent events, active scenarios, and available actors. Questions are designed
   * to drive interesting events and player engagement.
   *
   * **Generation Logic:**
   * - Generates 1-3 questions per call (random)
   * - Respects 20 question maximum (returns empty array if at capacity)
   * - Uses recent events for contextual continuity
   * - Avoids duplicating active questions
   * - Shuffles actors/orgs for variety
   *
   * **Resolution Timing:**
   * - LLM determines `daysUntilResolution` (1-7 days)
   * - Resolution date calculated from currentDate
   * - Clamped to valid range (1-7 days)
   *
   * **Question Properties:**
   * - `id`: Numeric ID starting from `nextQuestionId`
   * - `text`: LLM-generated question text
   * - `scenario`: Scenario ID this question relates to
   * - `outcome`: Predetermined outcome (true = YES, false = NO)
   * - `status`: Always 'active' for new questions
   * - `createdDate`: Current date
   * - `resolutionDate`: 1-7 days in the future
   *
   * @throws Never throws - returns empty array on error
   *
   * @example
   * ```typescript
   * const questions = await qm.generateDailyQuestions({
   *   currentDate: '2025-10-15',
   *   scenarios: gameScenarios,
   *   actors: mainActors,
   *   organizations: companies,
   *   activeQuestions: [...existingQuestions],
   *   recentEvents: [...recentDays],
   *   nextQuestionId: 42
   * });
   * // => [
   * //   { id: 42, text: "Will TechCorp announce...", outcome: true, ... },
   * //   { id: 43, text: "Will the scandal force...", outcome: false, ... }
   * // ]
   * ```
   */
  async generateDailyQuestions(
    params: QuestionCreationParams
  ): Promise<Question[]> {
    const {
      currentDate,
      scenarios,
      actors,
      organizations,
      activeQuestions,
      recentEvents,
      nextQuestionId,
    } = params;

    // Don't generate if we're at max capacity (20 questions)
    if (activeQuestions.length >= 20) {
      logger.warn(
        'Max 20 questions reached, skipping generation',
        undefined,
        'QuestionManager'
      );
      return [];
    }

    // Generate 1-3 new questions
    const numToGenerate = Math.min(
      Math.floor(Math.random() * 3) + 1, // 1-3 questions
      20 - activeQuestions.length // Don't exceed max
    );

    const currentDateObj = new Date(currentDate);

    // Build context from recent events
    const recentContext =
      recentEvents.length > 0
        ? `\n\nRECENT EVENTS (Last ${recentEvents.length} days):\n${recentEvents
            .slice(-5)
            .map(
              (day) =>
                `Day ${day.day}: ${day.events.map((e) => e.description).join('; ')}`
            )
            .join('\n')}`
        : '';

    // Build context from active questions
    const activeQuestionsContext =
      activeQuestions.length > 0
        ? `\n\nCURRENT ACTIVE QUESTIONS (${activeQuestions.length}/20):\n${activeQuestions
            .map((q) => `- ${q.text} (resolves ${q.resolutionDate})`)
            .join('\n')}`
        : '\n\nNo active questions yet.';

    const prompt = await this.buildQuestionGenerationPrompt(
      scenarios,
      actors,
      organizations,
      recentContext,
      activeQuestionsContext,
      numToGenerate
    );

    const rawResponse = await this.llm.generateJSON<
      | {
          questions: Array<{
            text: string;
            scenario: number;
            daysUntilResolution: number; // 1-7 days
            expectedOutcome: boolean;
          }>;
        }
      | {
          response: {
            questions: Array<{
              text: string;
              scenario: number;
              daysUntilResolution: number; // 1-7 days
              expectedOutcome: boolean;
            }>;
          };
        }
    >(prompt, undefined, {
      temperature: 0.9,
      maxTokens: 8000,
      promptType: 'question_generate_batch',
    });

    // Handle XML structure
    const response =
      'response' in rawResponse && rawResponse.response
        ? rawResponse.response
        : (rawResponse as {
            questions: Array<{
              text: string;
              scenario: number;
              daysUntilResolution: number;
              expectedOutcome: boolean;
            }>;
          });

    if (!response.questions || response.questions.length === 0) {
      logger.warn('LLM returned no questions', undefined, 'QuestionManager');
      return [];
    }

    // Convert to Question objects with dates and IDs
    const questions: Question[] = response.questions
      .slice(0, numToGenerate)
      .map((q, index) => {
        const resolutionDate = new Date(currentDateObj);
        resolutionDate.setDate(
          resolutionDate.getDate() + clamp(q.daysUntilResolution || 3, 1, 7)
        );

        return {
          id: nextQuestionId + index,
          text: q.text,
          scenario: q.scenario || 1,
          outcome: q.expectedOutcome,
          rank: 1,
          createdDate: currentDate,
          resolutionDate: toDateString(resolutionDate),
          status: 'active',
        };
      });

    return questions;
  }

  /**
   * Build LLM prompt for question generation
   */
  private async buildQuestionGenerationPrompt(
    scenarios: Scenario[],
    actors: SelectedActor[],
    organizations: Organization[],
    recentContext: string,
    activeQuestionsContext: string,
    numToGenerate: number
  ): Promise<string> {
    const scenariosList = scenarios
      .map(
        (s) => `
Scenario ${s.id}: ${s.title}
${s.description}
Actors: ${s.mainActors.join(', ')}
${s.involvedOrganizations?.length ? `Organizations: ${s.involvedOrganizations.join(', ')}` : ''}
`
      )
      .join('\n');

    // Shuffle actors and organizations to add variety to prompts
    const shuffledActors = shuffleArray(actors.filter(isEligibleActor));
    const actorsList = shuffledActors
      .slice(0, 20)
      .map((a) => `- ${a.name}: ${a.description}`)
      .join('\n');

    const shuffledOrgs = shuffleArray(
      organizations.filter((o) => o.type === 'company')
    );
    const orgsList = shuffledOrgs
      .slice(0, 15)
      .map((o) => `- ${o.name}: ${o.description}`)
      .join('\n');

    // Generate world context with reality grounding for better question quality
    const worldContext = await generateWorldContext({
      maxActors: 50,
      realityGroundingLevel: 'concise',
    });

    // Load example questions from TypeScript export
    let exampleQuestions = '';
    const { getQuestionExamples } = await import('./data/question-examples');
    const examples = getQuestionExamples();
    const shuffled = shuffleArray(examples);
    exampleQuestions = shuffled
      .slice(0, 10)
      .map((q) => `✅ "${q}"`)
      .join('\n');

    return renderPrompt(questionGeneration, {
      scenariosList,
      actorsList,
      orgsList,
      recentContext,
      activeQuestionsContext,
      numToGenerate: numToGenerate.toString(),
      exampleQuestions,
      ...worldContext,
    });
  }

  /**
   * Get questions that should be resolved today
   *
   * @param activeQuestions - Array of currently active questions
   * @param currentDate - Current date as ISO string (YYYY-MM-DD)
   * @returns Array of questions ready for resolution
   *
   * @description
   * Filters active questions to find those whose resolution date has been reached.
   * These questions should be resolved in the current game tick.
   *
   * **Resolution Criteria:**
   * - Question must have a `resolutionDate` set
   * - Resolution date must be <= current date
   * - Only checks active questions (not already resolved)
   *
   * **Typical Flow:**
   * 1. GameEngine calls this during tick
   * 2. For each returned question:
   *    - Generate resolution event
   *    - Call `resolveQuestion()`
   *    - Settle all positions
   *    - Update reputation
   *
   * @usage
   * Called by GameEngine every tick to check for questions ready to resolve.
   *
   * @example
   * ```typescript
   * const toResolve = qm.getQuestionsToResolve(activeQuestions, '2025-10-20');
   * // => [Question { id: 5, resolutionDate: '2025-10-19', ... }]
   *
   * for (const question of toResolve) {
   *   // Generate resolution event
   *   // Resolve question
   *   // Settle positions
   * }
   * ```
   */
  getQuestionsToResolve(
    activeQuestions: Question[],
    currentDate: string
  ): Question[] {
    const currentDateObj = new Date(currentDate);

    return activeQuestions.filter((q) => {
      if (!q.resolutionDate) return false;
      const resolutionDateObj = new Date(q.resolutionDate);
      return resolutionDateObj <= currentDateObj;
    });
  }

  /**
   * Resolve a question with final outcome
   *
   * @param question - Question to resolve
   * @param outcome - Final outcome (true = YES, false = NO)
   * @returns Resolved question with updated status and outcome
   *
   * @description
   * Marks a question as resolved and records the final outcome. This is a pure
   * function that returns a new question object - it does not mutate the input.
   *
   * **What This Does:**
   * - Sets `status` to 'resolved'
   * - Sets `resolvedOutcome` to the provided outcome
   * - Preserves all other question properties
   *
   * **What This Does NOT Do:**
   * - Does not settle positions (handled by GameEngine)
   * - Does not update reputation (handled by ReputationService)
   * - Does not persist to database (handled by GameEngine)
   * - Does not generate events (handled by GameEngine)
   *
   * @usage
   * Called by GameEngine after generating a resolution event.
   *
   * @example
   * ```typescript
   * const question = { id: 5, text: "Will...", outcome: true, status: 'active', ... };
   * const resolved = qm.resolveQuestion(question, true);
   * // => { ...question, status: 'resolved', resolvedOutcome: true }
   * ```
   */
  resolveQuestion(
    question: Question,
    outcome: boolean,
    resolutionDescription?: string,
    resolutionProofUrl?: string
  ): Question {
    return {
      ...question,
      status: 'resolved',
      resolvedOutcome: outcome,
      resolutionDescription,
      resolutionProofUrl,
    };
  }

  /**
   * Generate proof content (Article) for a resolved question
   */
  async generateProofContent(
    question: Question,
    eventDescription: string,
    actors: SelectedActor[],
    organizations: Organization[]
  ): Promise<{ type: 'article'; article: Article; url: string } | null> {
    const articleGenerator = new ArticleGenerator(this.llm);

    // Find a suitable media organization
    const mediaOrgs = organizations.filter((o) => o.type === 'media');
    // Use random media org or fallback to first org
    const org =
      mediaOrgs.length > 0
        ? mediaOrgs[Math.floor(Math.random() * mediaOrgs.length)]
        : organizations[0];

    if (!org) return null;

    // Create a synthetic event for the article generator
    const event: WorldEvent = {
      id: `resolution-${question.id}`,
      day: 0, // Placeholder, not critical for article generation logic here
      type: 'revelation',
      description: eventDescription,
      actors: [],
      relatedQuestion:
        typeof question.id === 'number' ? question.id : undefined,
      pointsToward: question.outcome ? 'YES' : 'NO',
      visibility: 'public',
    };

    // Get world facts context for article generation with graceful fallback
    let worldFactsContext = '';
    try {
      worldFactsContext = await worldFactsService.generatePromptContext();
    } catch (error) {
      logger.warn(
        'Failed to fetch world facts context for proof content - proceeding without',
        {
          questionId: question.id,
          error: formatError(error),
        },
        'QuestionManager'
      );
    }

    const article = await articleGenerator.generateArticleForQuestion(
      question,
      org,
      'resolution',
      actors,
      [event],
      worldFactsContext // World facts context for current game state
    );

    return {
      type: 'article',
      article,
      url: `/article/${article.id}`,
    };
  }

  /**
   * Generate resolution event and proof content
   */
  async generateResolutionWithProof(
    question: Question,
    actors: SelectedActor[],
    organizations: Organization[],
    recentEvents: DayTimeline[]
  ): Promise<ResolutionWithProof> {
    const description = await this.generateResolutionEvent(
      question,
      actors,
      organizations,
      recentEvents
    );

    // Generate proof
    const proof = await this.generateProofContent(
      question,
      description,
      actors,
      organizations
    );

    const evidenceText = [
      description,
      proof?.type === 'article' ? proof.article.title : null,
      proof?.type === 'article' ? proof.article.summary : null,
    ]
      .filter((s): s is string => typeof s === 'string' && s.trim().length > 0)
      .join('\n');

    // Guard: empty evidence should always trigger manual review
    if (!evidenceText.trim()) {
      return {
        description,
        proof: proof || undefined,
        confidence: RESOLUTION_CONFIDENCE_CONFIG.MIN_CONFIDENCE,
        requiresManualReview: true,
        confidenceSignals: ['no_evidence'],
      };
    }

    const assessment = this.assessResolutionConfidence(evidenceText);

    return {
      description,
      proof: proof || undefined,
      confidence: assessment.confidence,
      requiresManualReview: assessment.requiresManualReview,
      confidenceSignals: assessment.signals,
    };
  }

  private assessResolutionConfidence(text: string): {
    confidence: number;
    requiresManualReview: boolean;
    signals: string[];
  } {
    const signals: string[] = [];

    // Speculative signals with weights (higher = more speculative)
    // Patterns are designed to minimize false positives from common phrases
    const speculativeSignals: Array<[RegExp, string, number]> = [
      // High-weight: strong speculation indicators
      [/\brumou?r(s|ed)?\b/i, 'rumor', 0.25],
      [/\bunconfirmed\b/i, 'unconfirmed', 0.25],
      [/\balleged(ly)?\b/i, 'alleged', 0.2],
      [/\bsources?\s+(say|claim|suggest)\b/i, 'sources_say', 0.2],
      // Medium-weight: conditional language (stricter patterns to avoid false positives)
      [/\b(might|could)\s+(be|have|become|lead|cause)\b/i, 'conditional', 0.15],
      [/\bexpected\s+to\b/i, 'expected_to', 0.15],
      // More specific: "likely to be/happen" vs "the likely winner" (definitive)
      [/\blikely\s+to\s+(be|happen|occur|result)\b/i, 'likely', 0.12],
      // Low-weight: common but still speculative
      [/\breportedly\b/i, 'reportedly', 0.1],
      [/\bpossibly\b/i, 'possibly', 0.1],
      // More specific: "apparently uncertain" vs "apparently successful" (confirming)
      [
        /\bapparently\s+(not|uncertain|unclear|unconfirmed)\b/i,
        'apparently',
        0.08,
      ],
    ];

    let totalWeight = 0;
    for (const [regex, label, weight] of speculativeSignals) {
      if (regex.test(text)) {
        signals.push(label);
        totalWeight += weight;
      }
    }

    // Graduated confidence: start at base, subtract accumulated weight, floor at min
    const { BASE_CONFIDENCE, MIN_CONFIDENCE, MANUAL_REVIEW_THRESHOLD } =
      RESOLUTION_CONFIDENCE_CONFIG;
    const confidence = Math.max(MIN_CONFIDENCE, BASE_CONFIDENCE - totalWeight);

    return {
      confidence,
      requiresManualReview: confidence < MANUAL_REVIEW_THRESHOLD,
      signals,
    };
  }

  /**
   * Generate a resolution event that proves the question outcome
   *
   * @param question - Question being resolved
   * @param _actors - Available actors (currently unused, kept for interface compatibility)
   * @param _organizations - Available organizations (currently unused, kept for interface compatibility)
   * @param recentEvents - Recent game timeline for context
   * @returns Event description string that definitively proves the outcome
   *
   * @description
   * Uses LLM to generate a dramatic, definitive event that proves whether the
   * question outcome is YES or NO. This event provides closure to the narrative
   * and justifies position settlements.
   *
   * **Event Requirements:**
   * - Must be concrete and observable
   * - Must DEFINITIVELY prove the outcome
   * - Should reference recent related events for continuity
   * - Should be dramatic and satisfying for players
   *
   * **LLM Prompting:**
   * - Uses recent related events as context
   * - Instructs LLM to prove specific outcome (YES/NO)
   * - Temperature 0.7 for consistent but varied events
   * - Falls back to template if LLM fails
   *
   * @usage
   * Called by GameEngine when resolving questions.
   *
   * @example
   * ```typescript
   * const event = await qm.generateResolutionEvent(
   *   question,
   *   actors,
   *   organizations,
   *   recentTimeline
   * );
   * // => "TechCorp officially announces merger completion, signing ceremony held today"
   * ```
   */
  async generateResolutionEvent(
    question: Question,
    _actors: SelectedActor[],
    _organizations: Organization[],
    recentEvents: DayTimeline[]
  ): Promise<string> {
    // Get context from recent events related to this question
    const relatedEvents = recentEvents
      .flatMap((day) => day.events)
      .filter((e) => e.relatedQuestion === question.id)
      .slice(-3);

    const eventHistory =
      relatedEvents.length > 0
        ? `Recent events: ${relatedEvents.map((e) => e.description).join('; ')}`
        : 'No prior events';

    const outcomeContext = question.outcome
      ? 'PROVES it happened/succeeded'
      : 'PROVES it failed/was cancelled/did not happen';

    const prompt = renderPrompt(questionResolutionValidation, {
      questionText: question.text,
      outcome: question.outcome ? 'YES' : 'NO',
      eventHistory,
      contextInfo: '',
      outcomeContext,
    });

    const rawResponse = await this.llm.generateJSON<
      | { event: string; type: string }
      | { response: { event: string; type: string } }
    >(prompt, undefined, {
      temperature: 0.7,
      maxTokens: 5000,
      promptType: 'question_resolution_event',
    });

    // Handle XML structure
    const response =
      'response' in rawResponse && rawResponse.response
        ? rawResponse.response
        : (rawResponse as { event: string; type: string });

    const eventDescription =
      response.event ||
      `Resolution: ${question.text} outcome is ${question.outcome ? 'YES' : 'NO'}`;

    // Assess world impact
    await this.assessAndRecordWorldImpact(question, eventDescription);

    return eventDescription;
  }

  /**
   * Assess if a resolution event changes the world and record it if so
   */
  private async assessAndRecordWorldImpact(
    question: Question,
    resolutionEvent: string
  ): Promise<void> {
    const worldContext = await generateWorldContext({
      includeWorldFacts: true,
      realityGroundingLevel: 'concise',
    });

    const prompt = renderPrompt(worldImpactAssessment, {
      worldFacts: worldContext.worldFacts,
      questionText: question.text,
      outcome: question.outcome ? 'YES' : 'NO',
      outcomeText: question.outcome ? 'True/Happened' : 'False/Did not happen',
      resolutionEvent,
    });

    const response = await this.llm.generateJSON<
      | {
          changesWorld: boolean;
          newFact: string | null;
        }
      | {
          response: {
            changesWorld: boolean;
            newFact: string | null;
          };
        }
    >(prompt, undefined, { promptType: 'question_assess_world_impact' });

    // Handle potential wrapped response
    let result: { changesWorld: boolean; newFact: string | null };
    if ('response' in response) {
      result = response.response;
    } else {
      result = response;
    }

    if (result.changesWorld && result.newFact) {
      await worldFactsService.addDynamicFact(result.newFact);
      logger.info(
        `Added new world fact: ${result.newFact}`,
        { questionId: question.id },
        'QuestionManager'
      );
    }
  }

  /**
   * Get all active questions from a question array
   *
   * @param questions - Array of questions to filter
   * @returns Array of questions with status='active'
   *
   * @description
   * Simple filter utility to extract active questions. Active questions are
   * those that are currently tradable and generating events.
   *
   * @usage
   * Used by GameEngine to get questions for event generation.
   *
   * @example
   * ```typescript
   * const active = qm.getActiveQuestions(allQuestions);
   * // => [Question { status: 'active', ... }, Question { status: 'active', ... }]
   * ```
   */
  getActiveQuestions(questions: Question[]): Question[] {
    return questions.filter((q) => q.status === 'active');
  }

  /**
   * Get all resolved questions from a question array
   *
   * @param questions - Array of questions to filter
   * @returns Array of questions with status='resolved'
   *
   * @description
   * Simple filter utility to extract resolved questions. Useful for analytics,
   * displaying history, and calculating statistics.
   *
   * @usage
   * Used for displaying question history and analytics.
   *
   * @example
   * ```typescript
   * const resolved = qm.getResolvedQuestions(allQuestions);
   * // => [Question { status: 'resolved', resolvedOutcome: true, ... }]
   * ```
   */
  getResolvedQuestions(questions: Question[]): Question[] {
    return questions.filter((q) => q.status === 'resolved');
  }

  /**
   * Calculate days remaining until question resolves
   *
   * @param question - Question to check
   * @param currentDate - Current date as ISO string (YYYY-MM-DD)
   * @returns Number of days until resolution (0 if today/past, 999 if no resolution date)
   *
   * @description
   * Calculates the number of days from currentDate until the question's
   * resolutionDate. Used for urgency calculations and UI display.
   *
   * **Return Values:**
   * - `0`: Resolves today or already past
   * - `1-7`: Days remaining (normal range)
   * - `999`: No resolution date set (shouldn't happen)
   *
   * **Rounding:**
   * - Uses `Math.ceil()` to round up partial days
   * - Uses `Math.max(0)` to prevent negative values
   *
   * @usage
   * Used by FeedGenerator to adjust clue strength (closer = stronger clues).
   *
   * @example
   * ```typescript
   * const days = qm.getDaysUntilResolution(question, '2025-10-15');
   * // If resolutionDate is '2025-10-18':
   * // => 3
   *
   * const days = qm.getDaysUntilResolution(question, '2025-10-18');
   * // If resolutionDate is '2025-10-18':
   * // => 0 (resolves today)
   * ```
   */
  getDaysUntilResolution(question: Question, currentDate: string): number {
    if (!question.resolutionDate) return 999;

    const current = new Date(currentDate);
    const resolution = new Date(question.resolutionDate);
    const diffTime = resolution.getTime() - current.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    return Math.max(0, diffDays);
  }

  /**
   * Generate questions for continuous game mode with full context
   *
   * @param count - Number of questions to generate
   * @param deadlineMs - Deadline timestamp to abort if exceeded
   * @returns Number of questions successfully created
   *
   * @description
   * Generates questions with complete game context including:
   * - World facts and reality grounding
   * - Recent events (last 7 days)
   * - Active and resolved questions
   * - Actors and organizations
   * - Trending topics
   * - Current markets and trades
   *
   * Also creates markets and triggers NPC betting on new questions.
   */
  async generateQuestionsForContinuousGame(
    count: number,
    deadlineMs: number
  ): Promise<number> {
    let questionsCreated = 0;

    // Gather ALL context needed for intelligent question generation
    logger.info(
      'Gathering context for question generation...',
      { count },
      'QuestionManager'
    );

    const [
      worldFactsContext,
      worldContext,
      recentEvents,
      activeQuestions,
      resolvedQuestions,
      actorsList,
      organizationsList,
      trendingTagsList,
      marketMetrics,
    ] = await Promise.all([
      worldFactsService.generatePromptContext(),
      generateWorldContext({
        maxActors: 50,
        realityGroundingLevel: 'concise',
        includeMarkets: true,
        includePredictions: true,
        includeTrades: true,
        includeWorldFacts: true,
      }),
      // Get recent events from last 7 days
      db
        .select()
        .from(worldEvents)
        .where(
          and(
            gte(
              worldEvents.timestamp,
              new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
            ),
            eq(worldEvents.visibility, 'public')
          )
        )
        .orderBy(desc(worldEvents.timestamp))
        .limit(20),
      // Get active questions
      db
        .select()
        .from(questions)
        .where(eq(questions.status, 'active'))
        .orderBy(desc(questions.createdAt))
        .limit(20),
      // Get recently resolved questions (last 7 days) with outcomes
      db
        .select({
          text: questions.text,
          resolvedOutcome: questions.resolvedOutcome,
          resolutionDate: questions.resolutionDate,
        })
        .from(questions)
        .where(
          and(
            eq(questions.status, 'resolved'),
            gte(
              questions.updatedAt,
              new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
            )
          )
        )
        .orderBy(desc(questions.updatedAt))
        .limit(10),
      // Get actors (main and supporting roles, with tier fallback) from static registry
      Promise.resolve(
        StaticDataRegistry.getAllActors()
          .filter(isEligibleActor)
          .slice(0, 30)
          .map((a) => ({
            id: a.id,
            name: a.name,
            description: a.description,
            domain: a.domain,
            role: a.role,
            personality: a.personality,
            affiliations: a.affiliations,
          }))
      ),
      // Get organizations (companies) from static registry
      Promise.resolve(
        StaticDataRegistry.getAllOrganizations()
          .filter((o) => o.type === 'company')
          .slice(0, 20)
          .map((o) => ({
            id: o.id,
            name: o.name,
            description: o.description,
            type: o.type,
          }))
      ),
      // Get trending topics for context (with manual join for tags)
      db
        .select({
          id: trendingTags.id,
          tagId: trendingTags.tagId,
          score: trendingTags.score,
          tagName: tags.name,
          tagDisplayName: tags.displayName,
          tagCategory: tags.category,
        })
        .from(trendingTags)
        .leftJoin(tags, eq(trendingTags.tagId, tags.id))
        .orderBy(desc(trendingTags.score))
        .limit(10),
      // Get market metrics for metrics-based question generation (BAB-5)
      MarketMetricsService.gatherMetrics(24),
    ]);

    // Load example questions from TypeScript export
    let exampleQuestions = '';
    const { getQuestionExamples } = await import('./data/question-examples');
    const examples = getQuestionExamples();
    const shuffled = shuffleArray(examples);
    exampleQuestions = shuffled
      .slice(0, 10)
      .map((q) => `✅ "${q}"`)
      .join('\n');

    // Format context strings - compact format
    const recentEventsContext =
      recentEvents.length > 0
        ? `EVENTS(7d): ${recentEvents
            .slice(0, 10)
            .map((e) => `${e.description.substring(0, 60)}`)
            .join(' | ')}`
        : '';

    const activeQuestionsContext =
      activeQuestions.length > 0
        ? `ACTIVE(${activeQuestions.length}): ${activeQuestions
            .slice(0, 10)
            .map((q) => `"${q.text.substring(0, 50)}..."`)
            .join(' | ')}`
        : '';

    const resolvedQuestionsContext =
      resolvedQuestions.length > 0
        ? `RESOLVED(7d): ${resolvedQuestions
            .slice(0, 5)
            .map(
              (q) =>
                `"${q.text.substring(0, 40)}..."→${q.resolvedOutcome ? 'YES' : 'NO'}`
            )
            .join(' | ')}`
        : '';

    const actorsContext =
      actorsList.length > 0
        ? `ACTORS: ${actorsList
            .slice(0, 15)
            .map((a) => a.name)
            .join(', ')}`
        : '';

    const orgsContext =
      organizationsList.length > 0
        ? `COMPANIES: ${organizationsList
            .slice(0, 10)
            .map((o) => o.name)
            .join(', ')}`
        : '';

    const trendingContext =
      trendingTagsList.length > 0
        ? `TRENDING: ${trendingTagsList
            .slice(0, 5)
            .map((tt) => tt.tagDisplayName || tt.tagName || 'Unknown')
            .join(', ')}`
        : '';

    // Market metrics context (BAB-5: metrics-based question generation)
    const marketMetricsContext = marketMetrics.promptContext;

    // Build compact prompt
    const contextParts = [
      worldFactsContext,
      worldContext.realityGrounding || '',
      recentEventsContext,
      activeQuestionsContext,
      resolvedQuestionsContext,
      actorsContext,
      orgsContext,
      trendingContext,
      marketMetricsContext, // BAB-5: metrics-based question generation
      worldContext.currentMarkets
        ? `MARKETS: ${worldContext.currentMarkets}`
        : '',
      worldContext.activePredictions
        ? `PREDICTIONS: ${worldContext.activePredictions}`
        : '',
      worldContext.recentTrades ? `TRADES: ${worldContext.recentTrades}` : '',
      exampleQuestions ? `EXAMPLES: ${exampleQuestions}` : '',
    ]
      .filter(Boolean)
      .join('\n');

    const prompt = `Generate ${count} prediction market questions.

${contextParts}

RULES:
- Use EXACT parody names from lists (AIlon Musk, Sam AIltman, Mark Zuckerborg)
- YES/NO only, specific & measurable, future events, publicly verifiable
- NO resignations/acquisitions/relationship-breaking
- Resolution: 1-7 days (1-2d=fast, 3-5d=medium, 6-7d=slow)
- Don't duplicate active questions

TOPIC DIVERSITY (CRITICAL):
- Each question MUST be about a DIFFERENT topic/person/company
- Spread across: tech, crypto, politics, entertainment, business
- Use DIFFERENT actors for each question (not all about same person)
- Mix question types: product launches, price targets, announcements, partnerships
- NO two questions about the same actor or company in this batch

OUTCOME BALANCE:
- Aim for 40-60% yes/no split in expectedOutcome
- Not all questions should resolve the same way
- Include some questions likely to resolve NO

BAD: "Will X be happy?" (vague), "Will X secretly..." (unverifiable)

XML: <response><questions><question><text>...</text><resolutionCriteria>...</resolutionCriteria><daysUntilResolution>3</daysUntilResolution><expectedOutcome>yes</expectedOutcome></question></questions></response>`;

    // Generate questions in batch
    let response:
      | {
          questions: Array<{
            text: string;
            resolutionCriteria: string;
            daysUntilResolution: number;
            expectedOutcome: string; // "yes" or "no"
          }>;
        }
      | {
          response: {
            questions: Array<{
              text: string;
              resolutionCriteria: string;
              daysUntilResolution: number;
              expectedOutcome: string;
            }>;
          };
        }
      | null = null;

    if (Date.now() > deadlineMs) {
      logger.warn(
        'Question generation aborted due to tick budget limit',
        { questionsCreated },
        'QuestionManager'
      );
      return questionsCreated;
    }

    response = await this.llm.generateJSON<
      | {
          questions: Array<{
            text: string;
            resolutionCriteria: string;
            daysUntilResolution: number;
            expectedOutcome: string;
          }>;
        }
      | {
          response: {
            questions: Array<{
              text: string;
              resolutionCriteria: string;
              daysUntilResolution: number;
              expectedOutcome: string;
            }>;
          };
        }
    >(
      prompt,
      {
        properties: {
          questions: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                text: { type: 'string' },
                resolutionCriteria: { type: 'string' },
                daysUntilResolution: { type: 'number' },
                expectedOutcome: { type: 'string' },
              },
            },
          },
        },
        required: ['questions'],
      },
      {
        temperature: 0.9,
        maxTokens: 8000,
        format: 'xml',
        promptType: 'question_generate_real_world',
      }
    );

    // Handle XML structure - may be {questions: [...]} or {questions: {question: [...]}}
    type QuestionData = {
      text: string;
      resolutionCriteria: string;
      daysUntilResolution: number;
      expectedOutcome: string;
    };
    type QuestionsResponse = {
      questions: QuestionData[] | { question: QuestionData[] };
    };

    const rawQuestions =
      response && 'response' in response && response.response
        ? (response.response as QuestionsResponse).questions
        : (response as QuestionsResponse).questions;

    // Handle nested XML format {questions: {question: [...]}}
    const questionsData: QuestionData[] = Array.isArray(rawQuestions)
      ? rawQuestions
      : rawQuestions &&
          'question' in rawQuestions &&
          Array.isArray(rawQuestions.question)
        ? rawQuestions.question
        : [];

    if (questionsData.length === 0) {
      logger.warn(
        'No questions generated from LLM response',
        { response },
        'QuestionManager'
      );
      return questionsCreated;
    }

    // Get next question number
    const [lastQuestion] = await db
      .select({ questionNumber: questions.questionNumber })
      .from(questions)
      .orderBy(desc(questions.questionNumber))
      .limit(1);
    let nextQuestionNumber = (lastQuestion?.questionNumber ?? 0) + 1;

    // Using default scenario ID until dynamic scenario selection is implemented
    const scenarioId = 1;
    const now = new Date();
    const initialLiquidity = 20000;

    const marketService = new CorePredictionMarketService({
      db: new CorePredictionDbAdapter(),
      // Not used for market creation, but required by the service deps type
      wallet: {
        debit: async () => {},
        credit: async () => {},
        recordPnL: async () => {},
        getBalance: async () => ({ balance: 0 }),
      },
      fees: {
        tradingFeeRate: 0,
        platformShare: 0,
        referrerShare: 0,
        minFeeAmount: 0,
      },
    });

    // Create each question
    for (const questionData of questionsData.slice(0, count)) {
      if (Date.now() > deadlineMs) {
        logger.warn(
          'Question generation aborted due to tick budget limit',
          { questionsCreated },
          'QuestionManager'
        );
        break;
      }

      if (!questionData.text || !questionData.resolutionCriteria) {
        logger.warn(
          'Invalid question data, skipping',
          { questionData },
          'QuestionManager'
        );
        continue;
      }

      // Sanitize question text to remove any template variables that leaked through
      const sanitizedText = questionData.text
        .replace(/\{resolutionDate\}/gi, '')
        .replace(/\{resolution_date\}/gi, '')
        .replace(/\{date\}/gi, '')
        .replace(/\{[a-zA-Z_]+\}/g, '') // Remove any other template variables
        .replace(/\s+/g, ' ') // Normalize whitespace
        .replace(/by\s*\?$/i, '?') // Clean up "by ?" at end
        .trim();

      // Update the question text with sanitized version
      questionData.text = sanitizedText;

      // Convert "yes"/"no" to boolean
      const expectedOutcomeStr = String(questionData.expectedOutcome || '')
        .toLowerCase()
        .trim();
      const expectedOutcome =
        expectedOutcomeStr === 'yes' || expectedOutcomeStr === 'true';

      // Clamp daysUntilResolution to 1-7 range and ensure it's a valid integer
      const rawDays = questionData.daysUntilResolution;
      const daysUntilResolution = Math.max(
        1,
        Math.min(7, Math.round(rawDays || 3))
      );

      // Calculate resolution date from current date + daysUntilResolution
      const resolutionDate = new Date();
      resolutionDate.setDate(resolutionDate.getDate() + daysUntilResolution);
      resolutionDate.setHours(23, 59, 59, 999); // Set to end of day for consistency

      logger.info(
        `Creating question with ${daysUntilResolution} day resolution period`,
        {
          questionText: questionData.text,
          daysUntilResolution,
          resolutionDate: resolutionDate.toISOString(),
          rawDaysFromLLM: rawDays,
          expectedOutcome: expectedOutcomeStr,
          outcomeBoolean: expectedOutcome,
        },
        'QuestionManager'
      );

      const questionResults = await db
        .insert(questions)
        .values({
          id: await generateSnowflakeId(),
          questionNumber: nextQuestionNumber++,
          text: questionData.text,
          scenarioId,
          outcome: expectedOutcome,
          rank: 1,
          resolutionDate,
          status: 'active',
          updatedAt: now,
        })
        .returning();
      const question = firstOrThrow(
        questionResults,
        'Question insert returned empty'
      );

      // Ensure market exists via core service (keeps creation logic portable)
      const market = await marketService.ensureMarketExists({
        marketId: question.id,
        initialLiquidity,
        description: questionData.resolutionCriteria,
      });

      logger.debug(
        'Question and market created with matching resolution dates',
        {
          questionId: question.id,
          questionNumber: question.questionNumber,
          resolutionDate: resolutionDate.toISOString(),
          daysUntilResolution,
          marketEndDate: market.endDate.toISOString(),
        },
        'QuestionManager'
      );

      // Create and persist arc plan for this question
      const allActors = StaticDataRegistry.getAllActors()
        .filter(isEligibleActor)
        .slice(0, 30)
        .map((a) => ({
          id: a.id,
          name: a.name,
          description: a.description,
          tier: a.tier ?? undefined, // Convert null to undefined for type compatibility
          role: a.role,
          personality: a.personality,
          domain: a.domain,
          affiliations: a.affiliations,
        }));

      const allOrgs: Organization[] = StaticDataRegistry.getAllOrganizations()
        .filter((o) => o.type === 'company')
        .slice(0, 20)
        .map((o) => ({
          id: o.id,
          name: o.name,
          description: o.description,
          type: o.type as Organization['type'],
          canBeInvolved: o.canBeInvolved ?? true, // Default to true for backward compatibility
        }));

      const arcPlanner = new QuestionArcPlanner();
      const arcPlan = arcPlanner.planQuestionArc(
        {
          id: question.questionNumber,
          text: question.text,
          scenario: scenarioId,
          outcome: expectedOutcome,
          rank: 1,
          status: 'active',
        },
        allActors,
        allOrgs
      );

      // Save arc plan to database for use in subsequent ticks
      await saveArcPlan(question.id, arcPlan);

      // Create market on-chain if it doesn't have onChainMarketId
      if (!market.onChainMarketId) {
        await ensureMarketOnChain(market.id).catch((error: Error) => {
          logger.warn(
            'Failed to create market on-chain (non-blocking)',
            { error, marketId: market.id },
            'QuestionManager'
          );
        });
      }

      // Trigger NPC betting on this new question
      const contextService = new MarketContextService();

      // Create LLM client for market decisions
      const marketDecisionLLM = BabylonLLMClientValue.forGameTick();

      const modelName = process.env.MARKET_DECISION_MODEL || 'qwen/qwen3-32b';
      const isKimiModel = modelName.toLowerCase().includes('kimi');
      const defaultMaxOutput = isKimiModel ? 16000 : 32000;
      const maxOutputTokens = Number.parseInt(
        process.env.MARKET_DECISION_MAX_OUTPUT_TOKENS ||
          defaultMaxOutput.toString(),
        10
      );

      const decisionEngine = new MarketDecisionEngine(
        marketDecisionLLM,
        contextService,
        {
          model: modelName,
          maxOutputTokens,
        }
      );

      // Generate decisions for NPCs - they will see the new question in context
      const decisions = await decisionEngine.generateBatchDecisions();

      // Filter to decisions for this new question
      const questionDecisions = decisions.filter(
        (d) => d.marketType === 'prediction' && d.marketId === question.id
      );

      if (questionDecisions.length > 0) {
        const executionService = new TradeExecutionService();
        const executionResult =
          await executionService.executeDecisionBatch(questionDecisions);

        logger.info(
          `NPC betting on new question Q${question.questionNumber}`,
          {
            questionId: question.id,
            questionText: question.text,
            decisionsGenerated: questionDecisions.length,
            successfulTrades: executionResult.successfulTrades,
            failedTrades: executionResult.failedTrades,
          },
          'QuestionManager'
        );
      }

      questionsCreated++;
    }

    return questionsCreated;
  }

  /**
   * Generate a single question for a specific timeframe with full narrative context.
   *
   * @param timeframe - The market timeframe key (15m, 30m, 1h, 6h, 12h, 1d, 2d, 3d)
   * @param durationMs - Duration in milliseconds for this market
   * @returns Question details or null if generation fails
   *
   * @description
   * Generates a single question appropriate for the specified timeframe.
   * Uses full game context (world events, trending topics, active questions)
   * to create narrative-connected, non-repetitive questions.
   *
   * Timeframe categories:
   * - Short (15m, 30m, 1h): Immediate, observable events
   * - Medium (6h, 12h, 1d): Daily developments and announcements
   * - Long (2d, 3d): Multi-day narrative arcs
   */
  async generateTimeframeQuestion(
    timeframe: string,
    durationMs: number
  ): Promise<{
    text: string;
    resolutionCriteria: string;
    expectedOutcome: boolean;
    affiliatedActorIds: string[];
    affiliatedOrgIds: string[];
  } | null> {
    const category = this.getTimeframeCategory(timeframe);
    const durationLabel = this.getDurationLabel(durationMs);

    logger.info(
      `Generating ${timeframe} question (${category} category)`,
      { timeframe, durationMs, durationLabel },
      'QuestionManager'
    );

    // Gather comprehensive context (same as continuous game generation)
    const [
      worldFactsContext,
      recentEvents,
      activeQuestions,
      actorsList,
      organizationsList,
      trendingTagsList,
    ] = await Promise.all([
      worldFactsService.generatePromptContext(),
      // Get recent events - more recent for shorter timeframes
      db
        .select()
        .from(worldEvents)
        .where(
          and(
            gte(
              worldEvents.timestamp,
              new Date(Date.now() - this.getLookbackMs(category))
            ),
            eq(worldEvents.visibility, 'public')
          )
        )
        .orderBy(desc(worldEvents.timestamp))
        .limit(category === 'short' ? 10 : 20),
      // Get active questions to avoid duplication
      db
        .select()
        .from(questions)
        .where(eq(questions.status, 'active'))
        .orderBy(desc(questions.createdAt))
        .limit(20),
      // Get actors (with tier fallback since many actors don't have role defined)
      Promise.resolve(
        StaticDataRegistry.getAllActors()
          .filter(isEligibleActor)
          .slice(0, 20)
          .map((a) => ({
            id: a.id,
            name: a.name,
            description: a.description,
            domain: a.domain,
          }))
      ),
      // Get organizations
      Promise.resolve(
        StaticDataRegistry.getAllOrganizations()
          .filter((o) => o.type === 'company')
          .slice(0, 15)
          .map((o) => ({
            id: o.id,
            name: o.name,
            description: o.description,
          }))
      ),
      // Get trending topics
      db
        .select({
          tagName: tags.name,
          tagDisplayName: tags.displayName,
        })
        .from(trendingTags)
        .leftJoin(tags, eq(trendingTags.tagId, tags.id))
        .orderBy(desc(trendingTags.score))
        .limit(8),
    ]);

    // Build context strings
    const eventsContext =
      recentEvents.length > 0
        ? `RECENT EVENTS:\n${recentEvents
            .slice(0, 8)
            .map((e) => `- ${e.description}`)
            .join('\n')}`
        : '';

    const activeQContext =
      activeQuestions.length > 0
        ? `AVOID DUPLICATING:\n${activeQuestions
            .slice(0, 10)
            .map((q) => `- "${q.text}"`)
            .join('\n')}`
        : '';

    const actorsContext = `ACTORS: ${actorsList.map((a) => a.name).join(', ')}`;
    const orgsContext = `COMPANIES: ${organizationsList.map((o) => o.name).join(', ')}`;
    const trendingContext =
      trendingTagsList.length > 0
        ? `TRENDING: ${trendingTagsList.map((t) => t.tagDisplayName || t.tagName).join(', ')}`
        : '';

    // Timeframe-specific guidance
    const categoryGuidance = this.getCategoryGuidance(
      category,
      durationLabel,
      actorsList,
      organizationsList
    );

    const prompt = `Generate ONE prediction market question for a ${durationLabel} timeframe.

${worldFactsContext}

${eventsContext}

${activeQContext}

${actorsContext}
${orgsContext}
${trendingContext}

${categoryGuidance}

CRITICAL RULES:
- Must be binary (YES/NO answer only)
- Must be VERIFIABLE within ${durationLabel}
- Must use ONLY parody names (AIlon Musk, Sam AIltman, Mark Zuckerborg, Sim Cook, etc.)
- Must be SPECIFIC and ENGAGING
- Must be DIFFERENT from active questions listed above
- Keep under 100 characters
- If possible, BUILD ON a recent event to create narrative continuity

DIVERSITY REQUIREMENT:
- Make this question UNIQUE - not similar to existing active markets
- Draw inspiration from trending topics or recent events when possible
- Vary the subject (different actor/company than recent questions)

XML: <response><question><text>Your question here</text><resolutionCriteria>How to verify</resolutionCriteria><expectedOutcome>yes or no</expectedOutcome><primaryActor>Actor name if relevant</primaryActor><primaryOrg>Company name if relevant</primaryOrg></question></response>`;

    try {
      type QuestionResponse = {
        question?: {
          text: string;
          resolutionCriteria: string;
          expectedOutcome: string;
          primaryActor?: string;
          primaryOrg?: string;
        };
        response?: {
          question?: {
            text: string;
            resolutionCriteria: string;
            expectedOutcome: string;
            primaryActor?: string;
            primaryOrg?: string;
          };
        };
      };

      const response = await this.llm.generateJSON<QuestionResponse>(
        prompt,
        {
          properties: {
            question: {
              type: 'object',
              properties: {
                text: { type: 'string' },
                resolutionCriteria: { type: 'string' },
                expectedOutcome: { type: 'string' },
                primaryActor: { type: 'string' },
                primaryOrg: { type: 'string' },
              },
            },
          },
          required: ['question'],
        },
        {
          temperature: 0.85,
          maxTokens: 500,
          format: 'xml',
          promptType: 'generate_timeframe_question',
        }
      );

      // Handle XML structure variations
      const questionData =
        response?.question || response?.response?.question || null;

      if (!questionData?.text) {
        logger.warn(
          'Failed to generate timeframe question - empty response',
          { timeframe, response },
          'QuestionManager'
        );
        return null;
      }

      // Sanitize question text
      const sanitizedText = questionData.text
        .replace(/\{[a-zA-Z_]+\}/g, '')
        .replace(/\s+/g, ' ')
        .trim();

      // Parse expected outcome
      const outcomeStr = String(questionData.expectedOutcome || '')
        .toLowerCase()
        .trim();
      const expectedOutcome = outcomeStr === 'yes' || outcomeStr === 'true';

      // Find affiliated actor/org IDs
      const affiliatedActorIds: string[] = [];
      const affiliatedOrgIds: string[] = [];

      if (questionData.primaryActor) {
        const actor = actorsList.find(
          (a) =>
            a.name.toLowerCase() === questionData.primaryActor?.toLowerCase()
        );
        if (actor) affiliatedActorIds.push(actor.id);
      }

      if (questionData.primaryOrg) {
        const org = organizationsList.find(
          (o) => o.name.toLowerCase() === questionData.primaryOrg?.toLowerCase()
        );
        if (org) affiliatedOrgIds.push(org.id);
      }

      logger.info(
        `Generated ${timeframe} question`,
        { text: sanitizedText, expectedOutcome },
        'QuestionManager'
      );

      return {
        text: sanitizedText,
        resolutionCriteria:
          questionData.resolutionCriteria || 'Verifiable via public sources',
        expectedOutcome,
        affiliatedActorIds,
        affiliatedOrgIds,
      };
    } catch (error) {
      logger.error(
        'Failed to generate timeframe question',
        {
          error: formatError(error),
          timeframe,
        },
        'QuestionManager'
      );
      return null;
    }
  }

  /**
   * Get timeframe category from timeframe key
   */
  private getTimeframeCategory(timeframe: string): 'short' | 'medium' | 'long' {
    if (['15m', '30m', '1h'].includes(timeframe)) return 'short';
    if (['6h', '12h', '1d'].includes(timeframe)) return 'medium';
    return 'long'; // 2d, 3d
  }

  /**
   * Get human-readable duration label with proper pluralization
   */
  private getDurationLabel(durationMs: number): string {
    const minutes = Math.round(durationMs / 60000);
    if (minutes < 60) {
      return minutes === 1 ? '1 minute' : `${minutes} minutes`;
    }
    const hours = Math.floor(durationMs / (60 * 60 * 1000));
    if (hours < 24) {
      return hours === 1 ? '1 hour' : `${hours} hours`;
    }
    const days = Math.round(durationMs / (24 * 60 * 60 * 1000));
    return days === 1 ? '1 day' : `${days} days`;
  }

  /**
   * Get lookback period for context based on category
   */
  private getLookbackMs(category: 'short' | 'medium' | 'long'): number {
    switch (category) {
      case 'short':
        return 2 * 60 * 60 * 1000; // 2 hours
      case 'medium':
        return 24 * 60 * 60 * 1000; // 1 day
      case 'long':
        return 7 * 24 * 60 * 60 * 1000; // 7 days
    }
  }

  /**
   * Get category-specific prompt guidance
   */
  private getCategoryGuidance(
    category: 'short' | 'medium' | 'long',
    durationLabel: string,
    actors: Array<{ id: string; name: string }>,
    orgs: Array<{ id: string; name: string }>
  ): string {
    const actorExample = actors[0]?.name || 'AIlon Musk';
    const orgExample = orgs[0]?.name || 'Aipple';

    switch (category) {
      case 'short':
        return `SHORT-TERM QUESTION (${durationLabel}):
Generate questions about IMMEDIATE, OBSERVABLE events:
- Social media activity: "Will ${actorExample} post within ${durationLabel}?"
- Price movements: "Will ${orgExample} stock move 2%+ in ${durationLabel}?"
- Breaking news: "Will there be breaking news in the next ${durationLabel}?"
- Trading volume: "Will trading volume spike in the next ${durationLabel}?"
- Live events: Outcomes of ongoing events`;

      case 'medium':
        return `MEDIUM-TERM QUESTION (${durationLabel}):
Generate questions about DAILY developments:
- Announcements: "Will ${orgExample} announce something today?"
- Daily performance: "Will ${orgExample} close higher than it opened?"
- Actor statements: "Will ${actorExample} make a statement today?"
- Market trends: "Will crypto markets end the day green?"
- Scheduled events: Outcomes of planned meetings or releases`;

      case 'long':
        return `LONG-TERM QUESTION (${durationLabel}):
Generate questions about MULTI-DAY narratives:
- Investigations: "Will the investigation conclude within ${durationLabel}?"
- Major deals: "Will the merger be announced within ${durationLabel}?"
- Product launches: "Will ${orgExample} launch their product within ${durationLabel}?"
- Regulatory actions: "Will regulators take action within ${durationLabel}?"
- Leadership: "Will ${actorExample} make a major decision within ${durationLabel}?"`;
    }
  }
}
