/**
 * Prompt Logger
 *
 * Logs LLM prompts and responses to markdown files for monitoring and analysis.
 * Files are saved to: debug/prompts/<timestamp>_<promptType>.md
 *
 * Enable via environment variables:
 * - DEBUG_SAVE_PROMPTS=true
 * - DEBUG_PROMPTS=true
 */

import { logger } from '@babylon/shared';
import * as fs from 'fs';
import * as path from 'path';

export interface PromptLogEntry {
  promptType: string;
  promptTemplate?: string;
  input: string;
  output: string;
  parsedOutput?: string;
  metadata?: {
    provider?: string;
    model?: string;
    temperature?: number;
    maxTokens?: number;
    format?: string;
  };
}

/**
 * Check if prompt logging is enabled via environment variable
 */
export function isPromptLoggingEnabled(): boolean {
  return (
    process.env.DEBUG_SAVE_PROMPTS === 'true' ||
    process.env.DEBUG_SAVE_PROMPTS === '1' ||
    process.env.DEBUG_PROMPTS === 'true' ||
    process.env.DEBUG_PROMPTS === '1'
  );
}

/**
 * Log a prompt and its response to a markdown file
 */
export async function logPrompt(entry: PromptLogEntry): Promise<void> {
  if (!isPromptLoggingEnabled()) {
    return;
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safePromptType = entry.promptType.replace(/[^a-zA-Z0-9-_]/g, '_');
  const filename = `${timestamp}_${safePromptType}.md`;
  const debugDir = path.join(process.cwd(), 'debug', 'prompts');
  const filepath = path.join(debugDir, filename);

  // Ensure prompt log directory exists
  await fs.promises.mkdir(debugDir, { recursive: true });

  // Build markdown content
  const lines = [
    `# Prompt Debug Log: ${entry.promptType}`,
    ``,
    `**Timestamp:** ${new Date().toISOString()}`,
    ``,
  ];

  // Add metadata if present
  if (entry.metadata) {
    lines.push(`## Metadata`, ``);
    if (entry.metadata.provider)
      lines.push(`- **Provider:** ${entry.metadata.provider}`);
    if (entry.metadata.model)
      lines.push(`- **Model:** ${entry.metadata.model}`);
    if (entry.metadata.temperature !== undefined)
      lines.push(`- **Temperature:** ${entry.metadata.temperature}`);
    if (entry.metadata.maxTokens)
      lines.push(`- **Max Tokens:** ${entry.metadata.maxTokens}`);
    if (entry.metadata.format)
      lines.push(`- **Format:** ${entry.metadata.format}`);
    lines.push(``);
  }

  // Include prompt template in log if provided
  if (entry.promptTemplate) {
    lines.push(`## Prompt Template`, ``);
    lines.push('```');
    lines.push(entry.promptTemplate);
    lines.push('```');
    lines.push(``);
  }

  // Add rendered input
  lines.push(`# Input`, ``);
  lines.push('```');
  lines.push(entry.input);
  lines.push('```');
  lines.push(``);

  // Add raw output
  lines.push(`# Output`, ``);
  lines.push('```');
  lines.push(entry.output);
  lines.push('```');
  lines.push(``);

  // Add parsed output if available
  if (entry.parsedOutput) {
    lines.push(`## Parsed Output`, ``);
    lines.push('```json');
    lines.push(entry.parsedOutput);
    lines.push('```');
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Generated by Babylon Engine Prompt Logger`);
  lines.push(``);

  // Write to file
  await fs.promises.writeFile(filepath, lines.join('\n'), 'utf-8');

  logger.debug(
    `Logged prompt to ${filename}`,
    {
      promptType: entry.promptType,
      filepath,
    },
    'PromptLogger'
  );
}
