/**
 * Feedback history component for displaying user's received feedback.
 *
 * Displays a list of feedback items received by a user including ratings,
 * comments, and metadata. Shows feedback from games, trades, and user
 * interactions. Includes star ratings, category icons, and timestamps.
 * Auto-refreshes every 60 seconds.
 *
 * Features:
 * - Feedback list with ratings
 * - Star rating display
 * - Category icons
 * - Timestamp formatting
 * - Auto-refresh (60s interval)
 * - Filtering (auto-generated feedback)
 * - Loading states
 * - Empty state handling
 *
 * @param props - FeedbackHistory component props
 * @returns Feedback history element
 *
 * @example
 * ```tsx
 * <FeedbackHistory
 *   userId="user-123"
 *   limit={10}
 *   showAutoFeedback={true}
 * />
 * ```
 */
'use client';

import { getProfileUrl, logger } from '@babylon/shared';
import { formatDistanceToNow } from 'date-fns';
import {
  AlertCircle,
  MessageSquare,
  Star,
  TrendingDown,
  TrendingUp,
} from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';

/**
 * Feedback item structure for feedback history.
 */
interface FeedbackItem {
  id: string;
  fromUserId: string | null;
  fromUserName?: string;
  fromUsername?: string | null;
  score: number; // 0-100
  category: string | null;
  interactionType: string;
  comment: string | null;
  createdAt: string;
  isAutoGenerated: boolean;
  metadata?: {
    gameId?: string;
    tradeId?: string;
    positionId?: string;
  };
}

interface FeedbackHistoryProps {
  userId: string;
  limit?: number;
  showAutoFeedback?: boolean;
  className?: string;
}

export function FeedbackHistory({
  userId,
  limit = 10,
  showAutoFeedback = true,
  className = '',
}: FeedbackHistoryProps) {
  const [feedbackItems, setFeedbackItems] = useState<FeedbackItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [averageScore, setAverageScore] = useState<number>(0);

  useEffect(() => {
    const fetchFeedbackHistory = async () => {
      setLoading(true);
      try {
        const params = new URLSearchParams({
          limit: limit.toString(),
          includeAuto: showAutoFeedback.toString(),
        });
        const response = await fetch(
          `/api/feedback/received/${encodeURIComponent(userId)}?${params}`
        );
        if (!response.ok) {
          logger.error('Failed to fetch feedback history', {
            status: response.status,
            userId,
          });
          setLoading(false);
          return;
        }
        const data = await response.json();

        if (data.success) {
          setFeedbackItems(data.feedback || []);
          setAverageScore(data.averageScore || 0);
        }
      } catch (error) {
        logger.error('Error fetching feedback history', { error, userId });
      }
      setLoading(false);
    };

    fetchFeedbackHistory();
    // Refresh every 60 seconds
    const interval = setInterval(fetchFeedbackHistory, 60000);
    return () => clearInterval(interval);
  }, [userId, limit, showAutoFeedback]);

  const getStarRating = (score: number): number => {
    // Convert 0-100 score to 0-5 stars
    return Math.round((score / 100) * 5 * 10) / 10;
  };

  const getCategoryIcon = (category: string | null) => {
    switch (category) {
      case 'game_performance':
        return <TrendingUp className="h-3 w-3 text-green-500" />;
      case 'trade_execution':
        return <TrendingUp className="h-3 w-3 text-blue-500" />;
      case 'social_interaction':
        return <MessageSquare className="h-3 w-3 text-purple-500" />;
      default:
        return <Star className="h-3 w-3 text-gray-500" />;
    }
  };

  const getCategoryLabel = (category: string | null): string => {
    switch (category) {
      case 'game_performance':
        return 'Game';
      case 'trade_execution':
        return 'Trade';
      case 'social_interaction':
        return 'Social';
      default:
        return 'General';
    }
  };

  const truncateComment = (comment: string, maxLength = 100): string => {
    if (comment.length <= maxLength) return comment;
    return comment.slice(0, maxLength) + '...';
  };

  return (
    <div className={`rounded-lg bg-sidebar p-4 ${className}`}>
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <MessageSquare className="h-5 w-5 text-[#1c9cf0]" />
          <h2 className="font-bold text-foreground text-xl">
            Feedback History
          </h2>
        </div>
        {!loading && feedbackItems.length > 0 && (
          <div className="flex items-center gap-1 text-muted-foreground text-sm">
            <Star className="h-4 w-4 text-yellow-500" fill="currentColor" />
            <span className="font-semibold">
              {getStarRating(averageScore).toFixed(1)}
            </span>
            <span>/5</span>
          </div>
        )}
      </div>

      {loading ? (
        <div className="text-muted-foreground text-sm">Loading feedback...</div>
      ) : feedbackItems.length === 0 ? (
        <div className="text-muted-foreground text-sm">
          No feedback received yet. Complete games to receive feedback!
        </div>
      ) : (
        <div className="space-y-3">
          {feedbackItems.map((feedback) => {
            const feedbackDate = new Date(feedback.createdAt);
            const timeAgo = formatDistanceToNow(feedbackDate, {
              addSuffix: true,
            });
            const starRating = getStarRating(feedback.score);

            return (
              <div
                key={feedback.id}
                className="rounded-lg bg-muted/30 p-3 transition-colors hover:bg-muted/50"
              >
                {/* Header */}
                <div className="mb-2 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {feedback.isAutoGenerated ? (
                      <div className="flex items-center gap-1 text-blue-500 text-xs">
                        <AlertCircle className="h-3 w-3" />
                        <span>Auto-Generated</span>
                      </div>
                    ) : feedback.fromUserName ? (
                      <Link
                        href={getProfileUrl(
                          feedback.fromUserId || '',
                          feedback.fromUsername
                        )}
                        className="font-semibold text-foreground text-sm hover:underline"
                      >
                        {feedback.fromUserName}
                      </Link>
                    ) : (
                      <span className="text-muted-foreground text-sm">
                        System
                      </span>
                    )}
                    {feedback.category && (
                      <div className="flex items-center gap-1">
                        {getCategoryIcon(feedback.category)}
                        <span className="text-muted-foreground text-xs">
                          {getCategoryLabel(feedback.category)}
                        </span>
                      </div>
                    )}
                  </div>
                  <span className="text-muted-foreground text-xs">
                    {timeAgo}
                  </span>
                </div>

                {/* Star Rating */}
                <div className="mb-2 flex items-center gap-1">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <Star
                      key={star}
                      className={`h-4 w-4 ${
                        star <= Math.floor(starRating)
                          ? 'text-yellow-500'
                          : star <= starRating
                            ? 'text-yellow-500/50'
                            : 'text-gray-600'
                      }`}
                      fill={star <= starRating ? 'currentColor' : 'none'}
                    />
                  ))}
                  <span className="ml-1 text-muted-foreground text-sm">
                    {starRating.toFixed(1)}/5 ({feedback.score}/100)
                  </span>
                </div>

                {/* Comment */}
                {feedback.comment && (
                  <p className="line-clamp-2 break-words text-foreground text-sm">
                    {truncateComment(feedback.comment, 120)}
                  </p>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

/**
 * FeedbackSummaryCard Component
 *
 * Compact card showing feedback stats
 */
interface FeedbackSummaryCardProps {
  userId: string;
  className?: string;
}

export function FeedbackSummaryCard({
  userId,
  className = '',
}: FeedbackSummaryCardProps) {
  const [stats, setStats] = useState({
    averageScore: 0,
    totalFeedback: 0,
    recentTrend: 0,
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const response = await fetch(
          `/api/feedback/stats/${encodeURIComponent(userId)}`
        );
        if (!response.ok) {
          logger.error('Failed to fetch feedback stats', {
            status: response.status,
            userId,
          });
          setLoading(false);
          return;
        }
        const data = await response.json();

        if (data.success) {
          setStats({
            averageScore: data.averageScore || 0,
            totalFeedback: data.totalCount || 0,
            recentTrend: data.recentTrend || 0,
          });
        }
      } catch (error) {
        logger.error('Error fetching feedback stats', { error, userId });
      }
      setLoading(false);
    };

    fetchStats();
  }, [userId]);

  if (loading) return null;

  const starRating = Math.round((stats.averageScore / 100) * 5 * 10) / 10;

  return (
    <div className={`rounded-lg bg-muted/30 p-3 ${className}`}>
      <div className="flex items-center justify-between">
        <div>
          <div className="mb-1 flex items-center gap-1">
            <Star className="h-5 w-5 text-yellow-500" fill="currentColor" />
            <span className="font-bold text-2xl text-foreground">
              {starRating.toFixed(1)}
            </span>
            <span className="text-muted-foreground text-sm">/5</span>
          </div>
          <div className="text-muted-foreground text-xs">
            {stats.totalFeedback} review{stats.totalFeedback !== 1 ? 's' : ''}
          </div>
        </div>
        {stats.recentTrend !== 0 && (
          <div
            className={`flex items-center gap-1 font-medium text-xs ${
              stats.recentTrend > 0 ? 'text-green-500' : 'text-red-500'
            }`}
          >
            {stats.recentTrend > 0 ? (
              <TrendingUp className="h-4 w-4" />
            ) : (
              <TrendingDown className="h-4 w-4" />
            )}
            <span>{Math.abs(stats.recentTrend).toFixed(1)}%</span>
          </div>
        )}
      </div>
    </div>
  );
}
