/**
 * Prompt Debug Logger for @babylon/agents
 *
 * Logs all LLM prompts and responses to markdown files for debugging.
 * Files are saved as: debug/prompts/<timestamp>_<promptType>.md
 *
 * @packageDocumentation
 */

import * as fs from 'fs';
import * as path from 'path';
import { logger } from '../shared/logger';

export interface PromptLogEntry {
  promptType: string;
  promptTemplate?: string;
  input: string;
  output: string;
  parsedOutput?: string;
  metadata?: {
    provider?: string;
    model?: string;
    temperature?: number;
    maxTokens?: number;
    format?: string;
  };
}

/**
 * Checks if prompt logging is enabled via environment variable
 *
 * @returns True if DEBUG_SAVE_PROMPTS or DEBUG_PROMPTS is set to 'true' or '1'
 */
export function isPromptLoggingEnabled(): boolean {
  return (
    process.env.DEBUG_SAVE_PROMPTS === 'true' ||
    process.env.DEBUG_SAVE_PROMPTS === '1' ||
    process.env.DEBUG_PROMPTS === 'true' ||
    process.env.DEBUG_PROMPTS === '1'
  );
}

/**
 * Logs a prompt and its response to a markdown file
 *
 * @param entry - Prompt log entry with input, output, and metadata
 */
export async function logPrompt(entry: PromptLogEntry): Promise<void> {
  if (!isPromptLoggingEnabled()) {
    return;
  }

  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safePromptType = entry.promptType.replace(/[^a-zA-Z0-9-_]/g, '_');
    const filename = `${timestamp}_${safePromptType}.md`;
    const debugDir = path.join(process.cwd(), 'debug', 'prompts');
    const filepath = path.join(debugDir, filename);

    // Create debug directory if it doesn't exist
    await fs.promises.mkdir(debugDir, { recursive: true });

    // Build markdown content
    const lines = [
      `# Prompt Debug Log: ${entry.promptType}`,
      ``,
      `**Timestamp:** ${new Date().toISOString()}`,
      ``,
    ];

    // Add metadata if present
    if (entry.metadata) {
      lines.push(`## Metadata`, ``);
      if (entry.metadata.provider)
        lines.push(`- **Provider:** ${entry.metadata.provider}`);
      if (entry.metadata.model)
        lines.push(`- **Model:** ${entry.metadata.model}`);
      if (entry.metadata.temperature !== undefined)
        lines.push(`- **Temperature:** ${entry.metadata.temperature}`);
      if (entry.metadata.maxTokens)
        lines.push(`- **Max Tokens:** ${entry.metadata.maxTokens}`);
      if (entry.metadata.format)
        lines.push(`- **Format:** ${entry.metadata.format}`);
      lines.push(``);
    }

    // Add prompt template if available
    if (entry.promptTemplate) {
      lines.push(`## Prompt Template`, ``);
      lines.push('```');
      lines.push(entry.promptTemplate);
      lines.push('```');
      lines.push(``);
    }

    // Add rendered input
    lines.push(`# Input`, ``);
    lines.push('```');
    lines.push(entry.input);
    lines.push('```');
    lines.push(``);

    // Add raw output
    lines.push(`# Output`, ``);
    lines.push('```');
    lines.push(entry.output);
    lines.push('```');
    lines.push(``);

    // Add parsed output if available
    if (entry.parsedOutput) {
      lines.push(`## Parsed Output`, ``);
      lines.push('```json');
      lines.push(entry.parsedOutput);
      lines.push('```');
      lines.push(``);
    }

    lines.push(`---`);
    lines.push(`Generated by Babylon Prompt Logger`);
    lines.push(``);

    // Write to file
    await fs.promises.writeFile(filepath, lines.join('\n'), 'utf-8');

    logger.debug(
      `Logged prompt to ${filename}`,
      {
        promptType: entry.promptType,
        filepath,
      },
      'PromptLogger'
    );
  } catch (error) {
    logger.error(
      'Failed to log prompt debug file',
      {
        error: error instanceof Error ? error.message : String(error),
        promptType: entry.promptType,
      },
      'PromptLogger'
    );
  }
}

/**
 * Clean debug logs older than N days
 */
export async function cleanOldDebugLogs(maxAgeDays = 7): Promise<number> {
  if (!isPromptLoggingEnabled()) {
    return 0;
  }

  try {
    const debugDir = path.join(process.cwd(), 'debug', 'prompts');

    try {
      await fs.promises.access(debugDir);
    } catch {
      return 0;
    }

    const now = Date.now();
    const maxAgeMs = maxAgeDays * 24 * 60 * 60 * 1000;
    const files = await fs.promises.readdir(debugDir);

    let deleted = 0;
    for (const file of files) {
      if (!file.endsWith('.md')) continue;

      const filepath = path.join(debugDir, file);
      const stats = await fs.promises.stat(filepath);
      const age = now - stats.mtimeMs;

      if (age > maxAgeMs) {
        await fs.promises.unlink(filepath);
        deleted++;
      }
    }

    if (deleted > 0) {
      logger.info(
        `Cleaned up ${deleted} old debug logs`,
        { maxAgeDays },
        'PromptLogger'
      );
    }

    return deleted;
  } catch (error) {
    logger.error('Failed to clean debug logs', { error }, 'PromptLogger');
    return 0;
  }
}
