/**
 * Discord Activity OAuth Token Exchange API
 *
 * @route POST /api/auth/discord/activity - Exchange Discord Activity auth code for access token
 * @access Public (called from the Discord Activity iframe)
 *
 * @description
 * Handles the OAuth2 code exchange for Discord Activities (Embedded Apps).
 * The Discord Embedded App SDK calls `commands.authorize()` which returns a code.
 * This endpoint exchanges that code for an access_token, which is then passed back
 * to the client for `commands.authenticate()`.
 *
 * The `state` parameter must be a signed token generated by the
 * `GET /api/auth/discord/activity/state` endpoint. This prevents CSRF attacks
 * by ensuring the state was issued by this server and has not expired.
 */

import { withErrorHandling } from '@babylon/api';
import { logger } from '@babylon/shared';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { verifySignedState } from './state/state-utils';

const RequestSchema = z.object({
  code: z.string().min(1),
  state: z.string().min(1, 'OAuth state parameter is required'),
});

export const POST = withErrorHandling(async (request: NextRequest) => {
  const clientId =
    process.env.NEXT_PUBLIC_DISCORD_ACTIVITY_CLIENT_ID ||
    process.env.DISCORD_CLIENT_ID;
  // SECURITY: clientSecret is used exclusively for the Discord token exchange
  // request below. It must NEVER be logged, returned in responses, or passed
  // to any function that could serialize it.
  const clientSecret = process.env.DISCORD_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    logger.error(
      'Discord Activity token exchange failed: missing credentials',
      {},
      'DiscordActivity'
    );
    return NextResponse.json(
      { error: 'Discord Activity not configured' },
      { status: 500 }
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const parsed = RequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: 'Missing or invalid request parameters' },
      { status: 400 }
    );
  }

  const { code, state } = parsed.data;

  // Validate the signed state token — this is the server-side CSRF check.
  // The state must have been generated by our GET /api/auth/discord/activity/state
  // endpoint, be correctly signed with the client secret, and not have expired.
  const stateVerification = verifySignedState(state, clientSecret);
  if (!stateVerification.valid) {
    logger.warn(
      'Discord Activity token exchange rejected: invalid state',
      { reason: stateVerification.reason },
      'DiscordActivity'
    );
    return NextResponse.json(
      { error: 'Invalid or expired OAuth state parameter' },
      { status: 403 }
    );
  }

  logger.debug(
    'Discord Activity token exchange request validated',
    {},
    'DiscordActivity'
  );

  const tokenResponse = await fetch(
    'https://discord.com/api/v10/oauth2/token',
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: clientId,
        client_secret: clientSecret,
        grant_type: 'authorization_code',
        code,
      }),
    }
  );

  if (!tokenResponse.ok) {
    // SECURITY: Discord's error response may contain diagnostic info but
    // never echoes back the client_secret. We log the error text for
    // debugging but do not return it to the client.
    const errorText = await tokenResponse.text();
    logger.error(
      'Discord Activity token exchange failed',
      { status: tokenResponse.status, error: errorText },
      'DiscordActivity'
    );
    return NextResponse.json(
      { error: 'Token exchange failed' },
      { status: tokenResponse.status }
    );
  }

  const tokenData = (await tokenResponse.json()) as {
    access_token: string;
    token_type: string;
    expires_in: number;
    scope: string;
  };

  logger.info(
    'Discord Activity token exchange successful',
    { scope: tokenData.scope },
    'DiscordActivity'
  );

  return NextResponse.json({ access_token: tokenData.access_token });
});
